#!/usr/bin/env python3

import sys
from main import MainWindow

from PyQt5.QtWidgets import QApplication


if __name__ == '__main__':
    app = QApplication(sys.argv)
    m = MainWindow()
    sys.exit(app.exec_())

# vim: ts=4:sw=4:sts=4:expandtab
