# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_list.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageList(object):
    def setupUi(self, PageList):
        PageList.setObjectName("PageList")
        PageList.resize(529, 491)
        PageList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        PageList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(PageList)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(PageList)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.vmem_page = QtWidgets.QSpinBox(PageList)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.vmem_page.setFont(font)
        self.vmem_page.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vmem_page.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vmem_page.setSuffix("")
        self.vmem_page.setMaximum(4194303)
        self.vmem_page.setDisplayIntegerBase(16)
        self.vmem_page.setObjectName("vmem_page")
        self.horizontalLayout.addWidget(self.vmem_page)
        self.vmem_active = QtWidgets.QCheckBox(PageList)
        self.vmem_active.setObjectName("vmem_active")
        self.horizontalLayout.addWidget(self.vmem_active)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(PageList)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.directory = QtWidgets.QTableView(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.directory.setFont(font)
        self.directory.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.directory.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.directory.setObjectName("directory")
        self.gridLayout.addWidget(self.directory, 1, 0, 1, 1)
        self.table = QtWidgets.QTableView(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.table.setFont(font)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setObjectName("table")
        self.gridLayout.addWidget(self.table, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.translate_logical = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_logical.sizePolicy().hasHeightForWidth())
        self.translate_logical.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.translate_logical.setFont(font)
        self.translate_logical.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhPreferUppercase)
        self.translate_logical.setInputMask("")
        self.translate_logical.setMaxLength(8)
        self.translate_logical.setClearButtonEnabled(False)
        self.translate_logical.setObjectName("translate_logical")
        self.horizontalLayout_2.addWidget(self.translate_logical)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.translate_physical = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_physical.sizePolicy().hasHeightForWidth())
        self.translate_physical.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.translate_physical.setFont(font)
        self.translate_physical.setReadOnly(True)
        self.translate_physical.setObjectName("translate_physical")
        self.horizontalLayout_2.addWidget(self.translate_physical)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.supervisor = QtWidgets.QCheckBox(self.groupBox)
        self.supervisor.setEnabled(True)
        self.supervisor.setTristate(True)
        self.supervisor.setObjectName("supervisor")
        self.horizontalLayout_3.addWidget(self.supervisor)
        self.unwritable = QtWidgets.QCheckBox(self.groupBox)
        self.unwritable.setEnabled(True)
        self.unwritable.setTristate(True)
        self.unwritable.setObjectName("unwritable")
        self.horizontalLayout_3.addWidget(self.unwritable)
        self.unexecutable = QtWidgets.QCheckBox(self.groupBox)
        self.unexecutable.setEnabled(True)
        self.unexecutable.setTristate(True)
        self.unexecutable.setObjectName("unexecutable")
        self.horizontalLayout_3.addWidget(self.unexecutable)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(PageList)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PageList)

    def retranslateUi(self, PageList):
        _translate = QtCore.QCoreApplication.translate
        PageList.setWindowTitle(_translate("PageList", "Frame"))
        self.label.setText(_translate("PageList", "VMEM page"))
        self.vmem_page.setPrefix(_translate("PageList", "0x"))
        self.vmem_active.setText(_translate("PageList", "Active"))
        self.label_4.setText(_translate("PageList", "Virtual Memory is disabled"))
        self.label_2.setText(_translate("PageList", "Page Directory"))
        self.label_3.setText(_translate("PageList", "Page table"))
        self.groupBox.setTitle(_translate("PageList", "Translate address"))
        self.label_5.setText(_translate("PageList", "Logical"))
        self.translate_logical.setPlaceholderText(_translate("PageList", "(hex)"))
        self.label_6.setText(_translate("PageList", "-> Physical"))
        self.supervisor.setText(_translate("PageList", "Supervisor"))
        self.unwritable.setText(_translate("PageList", "Unwritable"))
        self.unexecutable.setText(_translate("PageList", "Unexecutable"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PageList = QtWidgets.QFrame()
    ui = Ui_PageList()
    ui.setupUi(PageList)
    PageList.show()
    sys.exit(app.exec_())

