#!/usr/bin/env babel-node

import TinyVM from '../src/tinyvm';
import Debugger from '../src/debugger';

var Canvas = require('canvas');  // TODO - remove this requirement
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

let canvas = new Canvas(500, 560);
let vm = new TinyVM(256, [], canvas, new Uint8Array());
let dbg = new Debugger(vm);

console.log(dbg.welcome());

rl.setPrompt('- ');
rl.prompt();

rl.on('line', (line) => {
  console.log(dbg.parse(line));
  rl.prompt();
});

// vim: ts=2:sw=2:sts=2:expandtab:syntax=javascript
