#!/usr/bin/env babel-node

var Canvas = require('canvas'),
    fs = require('fs');

//
// commandline arguments
//

if (process.argv.length !== 4) {
  console.error('Usage: genchars filename.png last_char');
  process.exit();
}

const filename = process.argv[2];
const lastChar = parseInt(process.argv[3]);

// 
// load file
//

fs.readFile(filename, (err, data) => {

  const print = process.stdout.write;

  if (err) {
    throw err;
  }

  const img = new Canvas.Image();
  img.src = data;

  let canvas = new Canvas(img.width, img.height);
  let ctx = canvas.getContext('2d');
  ctx.drawImage(img, 0, 0, img.width, img.height);

  process.stdout.write('var chars = [\n');

  for (let i = 0; i <= lastChar; ++i) {
    process.stdout.write(`  // char ${i}\n  [`);

    const ox = Math.floor(i / 16) * 6;
    const oy = (i % 16) * 9;
    
    let ns = [];
    for (let y = oy; y < (oy + 9); ++y) {
      let b = 0b0;
      for (let x = ox; x < (ox + 6); ++x) {
        b <<= 1;
        b |= (ctx.getImageData(x, y, 1, 1).data[0] == 0) ? 0 : 1;
      }
      ns.push('0x' + b.toString(16));
    }

    process.stdout.write(ns.join(', ') + '],\n\n');
  }

  process.stdout.write('];\n\nexport default chars;\n');
});

// vim: ts=2:sw=2:sts=2:expandtab:syntax=javascript
