#!/usr/bin/env babel-node

console.log('window.biosCode = new Uint8Array([' + require('fs').readFileSync(process.argv[2], 'binary').split('').map(c => c.charCodeAt(0)).join(',') + ']);');

// vim: ts=2:sw=2:sts=2:expandtab:syntax=javascript
