#!/usr/bin/env babel-node

console.log('export const data = new Uint8Array([' + require('fs').readFileSync(process.argv[2], 'binary').split('').map(c => '0x' + c.charCodeAt(0).toString(16)).join(', ') + ']);');

// vim: ts=2:sw=2:sts=2:expandtab:syntax=javascript
