#!/usr/bin/env lua

--
-- parse commandline arguments
--

if #arg ~= 2 then
  print('Usage: '..arg[0]..' filename.png last_char')
  os.exit(false)
end

--
-- load file
--

package.path = './libs/?.lua;' .. package.path
require('libs.png')

local img = pngImage(arg[1], nil)

print('var chars = [')

for i=1,arg[2] do
  print('  // char '..i)
  print('  [')

  -- get image
  local ox, oy = (i / 16) * 6, (i % 16) * 9

  print('  ],')
  print()
end

print('];')

-- vim: ts=2:sw=2:sts=2:expandtab
